The example that we are working with here is the idea that a restaurant serves three types of meals, but only one in a day.
If they serve one, they might either serve it again tomorrow, or any of the other two meals.
This scenario fits the Markov model in that what is served tomorrow is purely dependent on what was served today and not anything before. 

If we want to know, therefore, the probability table for tomorrow, we can use this to compute. We can also use this model to compute what they would serve in 15 days time (what they are most likely to serve)

If we extend the number of steps into infinity, we are able to obtain what the restaurant usually serves

All of this is implemented using the numpy class. To consider including deeper understanding of the subject through notes later

Library importation

In [1]:
import numpy as np

The next is now assigning the states with proper encoding. For example:
State 0 is burger
State 1 is Pizza
State 2 is Hotdog

We do this by the use of a dictionary

In [2]:
state = {
    0 : "burger",
    1 : "pizza",
    2 : "hotdog"
}

To see the contents of the dictionary, just call it directly

In [3]:
state

{0: 'burger', 1: 'pizza', 2: 'hotdog'}

To access using the index

In [6]:
state[0]
#When run, ir returns 'burger' as the string that is attached to that specific index

'burger'

To access using the name? We can revisit this later.

The next thing we want to do is the transition matrix for the model. The matrix is set such that the value in row j column k indicates the probabily of moving from the state in row k to the state in column j. We are reading from the left to the right.
We now implement the transition matrix

In [127]:
state_probability_matrix = np.array([[0.2, 0.6,0.2],[0.3,0,0.7],[0.5,0,0.5]])
#With that, we have created an array datatype which is a three by three matrix
#array([[0.2, 0.6, 0.2],
       #[0.3, 0. , 0.7],
       #[0.5, 0. , 0.5]])
#The 0.6, for example, is the probability of moving from row 1 (counting from 0) to colum 0 i.e from state 0 to 1 is from burger to pizza
state_probability_matrix

array([[0.2, 0.6, 0.2],
       [0.3, 0. , 0.7],
       [0.5, 0. , 0.5]])

First to confirm that none of the values in the transition matrix are more than 1

In [10]:
if sum(A[0]) + sum(A[1]) + sum(A[2]) !=3:
    print("Error, check the transition matrix")

And now to implement the markov model itself. This is done in the form of a function

In [107]:
def forecast(days):
    #First of all, we select what state we want to begin in
    start = 1 #Note that since we gave the name, the dictionary is able to pick this index automatically
    previous_state = start
    #print("The given start state is", state[start])
    while (days):
        current_state = np.random.choice([2,0,1],p = A[previous_state])
        #print(state[current_state], "-->", end = "")
        
        #print( state[current_state]) #This will print the entire chain of sequence of events
        print("The original start state is", state[start])
        print("The probability of moving out of this state is:", A[start])
        print("After the first iteration, the new start state is", state[current_state])
        print("current state:", A[current_state])
        # print("previous state:", A[previous_state])
        days-=1
    #print("stop")
    
#The only thing to understand over here is the random.choice method in numpy library.
#Its documentation is such that this is how we use it: we assign numpy.random.choice to a variable and can pass four arguments. the first is the array from which we want to pick a random number. After the array, we can also specify the size of the array. Then we can also set replace to True or False. True replace means that if the random number selected was index 4, it is not taken off the array. It is printed yes, but a copy of it is left in the array hence the array is left intact.
#The last argument is the probability related to each entry of the array

In [108]:
forecast(5)
#This is saying, if today we start with pizza, what are the probabilities for tomorrow? We expect for this to match the one on the table i.e
#array([[0.2, 0.6, 0.2],
       #[0.3, 0. , 0.7],
       #[0.5, 0. , 0.5]])
#pizza (1) to burger (0) should be 0.3, pizza (1) to pizza(1) 0 and pizza to hotdog is 0.7 - basically, just count row then column as you sweep through the direction.
#When run:
#  
#First time:
# The original start state is burger
# After the first iteration, the new start state is burger
# current state: [0.2 0.6 0.2]
# previous state: [0.2 0.6 0.2]

#Second time:
# The original start state is burger
# After the first iteration, the new start state is pizza
# current state: [0.3 0.  0.7]
# previous state: [0.2 0.6 0.2]

#Third time
# The original start state is burger
# After the first iteration, the new start state is burger
# current state: [0.2 0.6 0.2]
# previous state: [0.2 0.6 0.2]

#Fourth time
# The original start state is burger
# After the first iteration, the new start state is hotdog
# current state: [0.5 0.  0.5]
# previous state: [0.2 0.6 0.2]

#Fifth time
# The original start state is burger
# After the first iteration, the new start state is pizza
# current state: [0.3 0.  0.7]
# previous state: [0.2 0.6 0.2]

#This is basically us assuming that once we move to tomorrow, we are not thinking about today at all. Tomorrow is the new today.

#Note that one would think that the region with the highest probability is the one that will always be picked but this is not the case. The probability simply indicates that another region/route/food option can be chosen just not with as much frequency.

#The probability table, therefore, informs the algorithm with what probability to pick a certain specific food option. If a certain path, for example, has a probability of 0.2, it means that for every 10 choices for that root, there will be two set aside for that option within that specific path
#This is the incredible power of the random generator.
# 
#
# 
# 
# 
# 
# Point to be taken out of this is that you can either perform the prediction on a day to day basis or you could predict all the days at once.
# This algorithm is not very useful in the short term since with short term, there is some randomness. In the long run, however, we can predict which meals we are going to be making most of the times. 



The original start state is pizza
The probability of moving out of this state is: [0.3 0.  0.7]
After the first iteration, the new start state is hotdog
current state: [0.5 0.  0.5]
The original start state is pizza
The probability of moving out of this state is: [0.3 0.  0.7]
After the first iteration, the new start state is pizza
current state: [0.3 0.  0.7]
The original start state is pizza
The probability of moving out of this state is: [0.3 0.  0.7]
After the first iteration, the new start state is hotdog
current state: [0.5 0.  0.5]
The original start state is pizza
The probability of moving out of this state is: [0.3 0.  0.7]
After the first iteration, the new start state is pizza
current state: [0.3 0.  0.7]
The original start state is pizza
The probability of moving out of this state is: [0.3 0.  0.7]
After the first iteration, the new start state is pizza
current state: [0.3 0.  0.7]


Long term prediction - stationary probability.
Note that this accuracy reduces as we reduce on the amount of time for our prediction

In [148]:
def forecast(days):
    number_of_days = days
    start = 1 #this is the state from which we want to proceed
    i = 0
    state_where_we_are_now = start #This will keep on updating every time we make a move
    recorded_states = np.array([0,0,0])#all of them set to zero before
    while (days):
        state_where_we_go_to_next = np.random.choice([0,1,2],p = state_probability_matrix[state_where_we_are_now])
        state_where_we_are_now = state_where_we_go_to_next
        days-=1
    print("The state we began in is:", state[start], "but after", number_of_days, "iterations, the final state that we are in now is:", state[state_where_we_go_to_next])
    print(days) # This returns 0 because the 2 that we entered, if we were to print directly, is not being used as a number input but counter input. It is the one that informs the program to run through the loop twice. To see the actual number of days, we need to save it first as a constant variable then print it out
    print(number_of_days) # Now this returns the two that we expected

    # while i< d:
    #     recorded_states[]



In [149]:
forecast(2)

The state we began in is: pizza but after 2 iterations, the final state that we are in now is: burger
0
2


After this is now when we are moving to the long term prediction

In [193]:
def forecast(days):
    number_of_days = days
    start = 0 #this is the state from which we want to proceed
    state_where_we_are_now = start #This will keep on updating every time we make a move
    recorded_states = np.array([0,0,0])#all of them set to zero before
    recorded_states[start] = 1 #This is to instruct the application that even before we begin, we already have 1 observation of the beginning state (at the time of writing, start = 0 which means that we are initalising this array to indicate that burger - state 0 - has already been seen once)

    # #This is an extra step to extract the index from the dictionary
    # keys = state.keys()
    # values = state.values() # These are methods to access items in the dictionary

    print ("Initial recorded state is:" , state[start], "after which the order of the states in the specified number of iterations is:")
    i = 0
    while (days):
        state_where_we_go_to_next = np.random.choice([0,1,2],p = state_probability_matrix[state_where_we_are_now])
        state_where_we_are_now = state_where_we_go_to_next
        recorded_states[state_where_we_go_to_next] +=1 #What this does not do is create an array of every state once it has been chosen. It simply counts. For example, if we find out that out next state is state 1, it will go to its memory and check, at what number did we stop with state 1? Then increment it by 1. To compute average, divide each element with the days
        days-=1
        print(state[state_where_we_go_to_next])
    
    print("A tally of the recorded states reveals that states 0 (burger), 1(pizza) and 2(hotdog) are observed in a totality as respectively:", recorded_states)
    print("When averaged out, this returns", recorded_states/number_of_days)




In [196]:
forecast(2)

Initial recorded state is: burger after which the order of the states in the specified number of iterations is:
burger
pizza
A tally of the recorded states reveals that states 0 (burger), 1(pizza) and 2(hotdog) are observed in a totality as respectively: [2 1 0]
When averaged out, this returns [1.  0.5 0. ]


For longer iterations to find the steady state behaviour

In [199]:
def forecast(days):
    number_of_days = days
    start = 0 #this is the state from which we want to proceed
    state_where_we_are_now = start #This will keep on updating every time we make a move
    recorded_states = np.array([0,0,0])#all of them set to zero before
    recorded_states[start] = 1 #This is to instruct the application that even before we begin, we already have 1 observation of the beginning state (at the time of writing, start = 0 which means that we are initalising this array to indicate that burger - state 0 - has already been seen once)

    while (days):
        state_where_we_go_to_next = np.random.choice([0,1,2],p = state_probability_matrix[state_where_we_are_now])
        state_where_we_are_now = state_where_we_go_to_next
        recorded_states[state_where_we_go_to_next] +=1 #What this does not do is create an array of every state once it has been chosen. It simply counts. For example, if we find out that out next state is state 1, it will go to its memory and check, at what number did we stop with state 1? Then increment it by 1. To compute average, divide each element with the days
        days-=1
        #print(state[state_where_we_go_to_next])
    
    print("A tally of the recorded states reveals that states 0 (burger), 1(pizza) and 2(hotdog) are observed in a totality as respectively:", recorded_states)
    print("When averaged out, this returns", recorded_states/number_of_days)

In [200]:
forecast(10000)

A tally of the recorded states reveals that states 0 (burger), 1(pizza) and 2(hotdog) are observed in a totality as respectively: [3484 2110 4407]
When averaged out, this returns [0.3484 0.211  0.4407]


In this section, we are mostly dealing with dictionaries or dataframes. Worth practising a bit more to understand the nitty grities of the data storage approach